const CONNECTOR_DEFINITIONS = Object.freeze([
  Object.freeze({
    id: "zoho-desk",
    type: "zoho-desk",
    name: "Zoho Desk",
    description: "只读工单分诊、指标和当前工单上下文",
    icon: "ticket",
    capabilities: ["query", "trigger"],
    supportedAuthTypes: ["oauth2-pkce"],
    version: "1.0.0",
    implemented: true,
    readOnly: true,
  }),
  Object.freeze({
    id: "emma",
    type: "emma",
    name: "Emma 知识库",
    description: "知识检索连接器契约；当前未配置正式接口",
    icon: "search",
    capabilities: ["query"],
    supportedAuthTypes: ["api-key"],
    version: "0.1.0",
    implemented: false,
    readOnly: true,
  }),
  Object.freeze({
    id: "customer-ops",
    type: "customer-ops",
    name: "Customer Ops",
    description: "客户与系统环境上下文连接器契约",
    icon: "database",
    capabilities: ["query"],
    supportedAuthTypes: ["service-token"],
    version: "0.1.0",
    implemented: false,
    readOnly: true,
  }),
  Object.freeze({
    id: "gitee",
    type: "gitee",
    name: "Gitee",
    description: "仅展示外部对象关联；不创建 Issue",
    icon: "external",
    capabilities: ["query"],
    supportedAuthTypes: ["api-token"],
    version: "0.1.0",
    implemented: false,
    readOnly: true,
  }),
  Object.freeze({
    id: "b1-support-hub",
    type: "b1-support-hub",
    name: "B1 运维台",
    description: "运维上下文连接器预留",
    icon: "database",
    capabilities: ["query"],
    supportedAuthTypes: ["service-token"],
    version: "0.1.0",
    implemented: false,
    readOnly: true,
  }),
]);

module.exports = { CONNECTOR_DEFINITIONS };
